### ISSUE TITLE
Need to swap colors for Diff file format in Mocha theme

### ISSUE THREAD

**Issue by git58** [catppuccin/ksyntaxhighlighting#1]
Now we have: 
- pink color for Added line and Changed line (new)
- green color for Removed line and Changed line (old)

**Comment by Sourcastic** [comment]
I've made a commit to change them around to match the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md). Do test them out!

**Comment by Sourcastic** [comment]
Anyway, I think I've fixed this and can close the issue. Feel free to leave a comment or open another issue if you think it needs re-opening.
